#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := continuos_ranging

EXTRA_COMPONENT_DIRS := ../../

include $(IDF_PATH)/make/project.mk

